Hotel/Pages/AddAdmin.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class AddAdminModel : PageModel
    {
        private readonly ILogger<AddAdminModel> _logger;
        private readonly dbclass _t1;
        public AddAdminModel(ILogger<AddAdminModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }

        [BindProperty]
        public string name { get; set; }
        [BindProperty]
        public string username { get; set; }
        [BindProperty]
        public string password { get; set; }
        [BindProperty]
        public string message { get; set; }

        public void OnGet()
        {

        }
        public IActionResult OnPostSubmit()
        {
            message = _t1.InsertAdmin(username, password);
            return RedirectToPage("/Admin");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Admin");

        }
    }
}

Hotel/Pages/AddManager.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class AddManagerModel : PageModel
    {
        private readonly ILogger<AddManagerModel> _logger;
        private readonly dbclass _t1;
        public AddManagerModel(ILogger<AddManagerModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }

        [BindProperty]
        public string name { get; set; }
        [BindProperty]
        public string username { get; set; }
        [BindProperty]
        public string password { get; set; }
        [BindProperty]
        public string message { get; set; }

        public void OnGet()
        {
            
        }
        public IActionResult OnPostSubmit()
        {
            message=_t1.InsertManager(username,password,name,1,1,1);
            return RedirectToPage("/Admin");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Admin");

        }
        
    }
}

Hotel/Pages/AddRoom.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class AddRoomModel : PageModel
    {
        private readonly ILogger<AddRoomModel> _logger;
        private readonly dbclass _t1;
        public AddRoomModel(ILogger<AddRoomModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }

        [BindProperty]
        public string CategoryName { get; set; }

        [BindProperty]
        public int Roomn { get; set; }
        [BindProperty]
        public int Price { get; set; }
        [BindProperty]
        
        public string message { get; set; }

        public void OnGet()
        {
            Table = _t1.ShowTable("RoomType");

        }
        public IActionResult OnPostSubmit()
        {
            
            message = _t1.InsertRoom(Roomn, CategoryName, Price);
            return RedirectToPage("/Admin");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Admin");

        }
    }
}

Hotel/Pages/AddRoomType.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class AddRoomTypeModel : PageModel
    {
        private readonly ILogger<AddRoomTypeModel> _logger;
        private readonly dbclass _t1;
        public AddRoomTypeModel(ILogger<AddRoomTypeModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }

        [BindProperty]
        public string CategoryName { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string photo { get; set; }
        [BindProperty]
        public int Price { get; set; }
        [BindProperty]
        public int bed { get; set; }
        [BindProperty]
        public int bath { get; set; }
        [BindProperty]
        public string message { get; set; }

        public void OnGet()
        {

        }
        public IActionResult OnPostSubmit()
        {
            Table = _t1.ShowTable("RoomType");
            message = _t1.InsertRoomType(Table.Rows.Count + 1, CategoryName,Price, Description,bed,bath,photo);
            return RedirectToPage("/Admin");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Admin");

        }
    }
}

Hotel/Pages/AddServes.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class AddServesModel : PageModel
    {
        private readonly ILogger<AddServesModel> _logger;
        private readonly dbclass _t1;
        public AddServesModel(ILogger<AddServesModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }

        [BindProperty]
        public string ServesName { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string icon { get; set; }
        [BindProperty]
        public int Price { get; set; }
        
        
        [BindProperty]
        public string message { get; set; }

        public void OnGet()
        {

        }
        public IActionResult OnPostSubmit()
        {
            Table = _t1.ShowTable("Serves");
            message = _t1.InsertService(Table.Rows.Count + 1, ServesName, Description, 1,Price, icon);
            return RedirectToPage("/Admin");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Admin");

        }
    }
}

Hotel/Pages/AddStaff.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class AddStaffModel : PageModel
    {
        private readonly ILogger<AddStaffModel> _logger;
        private readonly dbclass _t1;
        public AddStaffModel(ILogger<AddStaffModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }
        public DataTable Table2 { get; set; }
        public DataTable Table3 { get; set; }
        public DataTable Table4 { get; set; }


        [BindProperty]
        public string name { get; set; }
        [BindProperty]
        public string username { get; set; }
        [BindProperty]
        public string password { get; set; }
        [BindProperty]
        public string manager { get; set; }
        [BindProperty]
        public string Role { get; set; }
        [BindProperty]
        public string Admin { get; set; }
        [BindProperty]
        public string message { get; set; }

        public void OnGet()
        {
            Table = _t1.ShowTable("Admin");
            Table2 = _t1.ShowTable("Manager");
            Table3 = _t1.ShowTable("StafRoles");
        }
        public IActionResult OnPostSubmit()
        {
            Table4 = _t1.ShowTable("Staff");
            message = _t1.InsertStaff(Table4.Rows.Count+1,1,username,password,name,Role,manager,Admin);
            return RedirectToPage("/Admin");
        }
        public IActionResult OnPostCancel()
        {
            return RedirectToPage("/Admin");

        }
        
    }
}

Hotel/Pages/Admin.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel.Pages
{
    public class AdminModel : PageModel
    {
        private ILogger<AdminModel> _logger;
        private dbclass t1;

        [BindProperty(SupportsGet = true)]
        public string Username { get; set; }
        [BindProperty]
        public string Username1 { get; set; }

        public AdminModel(ILogger<AdminModel> logger, dbclass t1)
        {
            _logger = logger;
            this.t1 = t1;
        }
        public void OnGet()
        {
            Username1 = t1.AUsername;
        }
        public IActionResult OnPostSubmit()
        {

            return RedirectToPage("/Manager");
        }
        public IActionResult OnPostSubmit1()
        {

            return RedirectToPage("/AddManager");
        }
        public IActionResult OnPostSubmit2()
        {

            return RedirectToPage("/AddStaff");
        }
        public IActionResult OnPostSubmit3()
        {

            return RedirectToPage("/AddAdmin");
        }
        public IActionResult OnPostSubmit4()
        {

            return RedirectToPage("/AddRoomType");
        }
        public IActionResult OnPostSubmit5()
        {

            return RedirectToPage("/AddServes");
        }
        public IActionResult OnPostSubmit6()
        {

            return RedirectToPage("/AddRoom");
        }

    }
}

Hotel/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Hotel.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Hotel/Pages/Index.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private dbclass t1;
        public DataTable Table { get; set; }
        public DataTable Table1 { get; set; }
        public DataTable Table2 { get; set; }
        public IndexModel(ILogger<IndexModel> logger, dbclass t1)
        {
            _logger = logger;
            this.t1 = t1;
        }
        
        

        
        
        public void OnGet()
        {
            Table = t1.ShowFeadbackTable();
            Table1 = t1.ShowTable("Services");
            Table2 = t1.ShowTable("RoomType");
        }
        
    }
}

Hotel/Pages/Login SingUp.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Threading.Tasks;

namespace Hotel.Pages
{
    public class Login_SingUpModel : PageModel
    {
        [BindProperty]
        [Required(ErrorMessage = "Username is required.")]
        public string Username { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string UserError { get; set; }
        public string Guest { get; set; }

        private readonly ILogger<Login_SingUpModel> _logger;
        private readonly dbclass _t1;

        public Login_SingUpModel(ILogger<Login_SingUpModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost()
        {
            _logger.LogInformation("Login attempt for Username: {Username}", Username);

            if (ModelState.IsValid)
            {
                DataRow userRow = _t1.GetUser("Guest", Username, Password);

                if (userRow != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, Username),
                        new Claim(ClaimTypes.Role, "Guest")
                    };

                    var claimsIdentity = new ClaimsIdentity(
                        claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = true
                    };

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);

                    _t1.username1(Username);
                    _logger.LogInformation("Login successful for Username: {Username}", Username);
                    return RedirectToPage("/Userpage", new { Username = Username });
                }
            }
            UserError = "Username or password are incorrect";
            _logger.LogWarning("Login failed for Username: {Username}. UserError: {UserError}", Username, UserError);
            return Page();
        }
    }
}

Hotel/Pages/Manager.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;

namespace Hotel.Pages
{
    public class ManagerModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        
        public string Username1 { get; set; }

        private readonly ILogger<ManagerModel> _logger;
        private readonly dbclass _t1;
        public ManagerModel(ILogger<ManagerModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }
        public DataTable Table1 { get; set; }
        public DataTable Table2 { get; set; }
        public DataTable Table3 { get; set; }
        public DataTable Table4 { get; set; }
        public DataTable Table5 { get; set; }
        public DataTable Table6 { get; set; }
        public DataTable Table7 { get; set; }
        public DataTable Table8 { get; set; }
        public DataTable Table9 { get; set; }
        public DataTable Table10 { get; set; }
        public void OnGet()
        {
            Username1 = _t1.AUsername;

            Table = _t1.ShowTable("Admin");
            Table2 = _t1.ShowTable("Manager");
            Table3 = _t1.ShowTable("Staff");
            Table4 = _t1.ShowTable("Guest");
            Table5 = _t1.ShowTable("RoomType");
            Table6 = _t1.ShowTable("Room");
            Table7 = _t1.ShowTable("Reservation");
            Table8 = _t1.ShowTable("RoomManager");
            Table9 = _t1.ShowTable("Services");
            Table10 = _t1.ShowTable("Feedback");

        }

    }
}

Hotel/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Hotel/Pages/ReservationHistory.cshtml.cs
using Hotel.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using Microsoft.AspNetCore.Authorization; // Added for [Authorize]

namespace Hotel.Pages
{
    [Authorize] // Added to protect this page
    public class ReservationHistoryModel : PageModel
    {
        // Removed Username and Username1 properties as User.Identity.Name will be used directly
        // [BindProperty(SupportsGet = true)]
        // public string Username { get; set; }
        // public string Username1 { get; set; }

        private readonly ILogger<ReservationHistoryModel> _logger;
        private readonly dbclass _t1;
        public ReservationHistoryModel(ILogger<ReservationHistoryModel> logger, dbclass t1)
        {
            _logger = logger;
            _t1 = t1;
        }
        public DataTable Table { get; set; }
        public void OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                // Username1 = User.Identity.Name; // Not needed as User.Identity.Name can be used directly
                Table = _t1.ShowReservationHistoryTable(User.Identity.Name);
            }
            else
            {
                RedirectToPage("/Login SingUp"); // Should not happen with [Authorize]
            }
        }
    }
}

Hotel/Pages/about.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel.Pages
{
    public class aboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hotel/Pages/event.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotel.Pages
{
    public class eventModel : PageModel
    {

        public void OnGet()
        {
        }
    }
}

Hotel/Pages/AddManager.cshtml
@page
@model Hotel.Pages.AddManagerModel
@{
    ViewData["Title"] = "Add Manager";
}

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-success" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />

<div class="text-left">
    <br />
    <h1 class="text-lg-center fs-5">Add Manager</h1>
    <form method="post">
        <label class="form-label " for="ID">Username:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.username">

        <label class="form-label mt-1" for="name,">Name:</label>
        <input class="form-control mb-2" type="text"  asp-for="@Model.name">

        

        <label class="form-label mt-1" for="name,">Password:</label>
        <input class="form-control mb-2" type="password" asp-for="@Model.password">

        <button asp-page-handler="submit" class="btn btn-success mt-2">Add</button>
        <button asp-page-handler="cancel" class="btn btn-outline-secondary mt-2">Cancel</button>
    </form>

</div>

Hotel/Pages/AddRoom.cshtml
@page
@model Hotel.Pages.AddRoomModel
@{
    ViewData["Title"] = "Add Room";
}

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-success" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />

<div class="text-left">
    <br />
    <h1 class="text-lg-center fs-5">Add Serves</h1>
    <form method="post">
        <label class="form-label " for="ID">Room Number:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.Roomn">\

        <label class="form-label mt-1" for="name,">CategoryName:</label>
        <select asp-for="@Model.CategoryName" class="form-select text-black bg-transparent">
            <option class="text-black" selected disabled>Select your Room</option>
            @for (int i = 0; i < @Model.Table.Rows.Count; i++)
            {
                <option class="text-black" value="@Model.Table.Rows[i][1]">@Model.Table.Rows[i][1]</option>
            }
        </select>

        <label class="form-label mt-1" for="name,">Price:</label>
        <input class="form-control mb-2" type="number" asp-for="@Model.Price">

        <button asp-page-handler="submit" class="btn btn-success mt-2">Add</button>
        <button asp-page-handler="cancel" class="btn btn-outline-secondary mt-2">Cancel</button>
    </form>

</div>

Hotel/Pages/AddRoomType.cshtml
@page
@model Hotel.Pages.AddRoomTypeModel
@{
    ViewData["Title"] = "Add Admin";
}

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-success" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />

<div class="text-left">
    <br />
    <h1 class="text-lg-center fs-5">Add RoomType</h1>
    <form method="post">
        <label class="form-label " for="ID">Category Name:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.CategoryName">


        <label class="form-label mt-1" for="name,">Price:</label>
        <input class="form-control mb-2" type="number" asp-for="@Model.Price">

        <label class="form-label mt-1" for="name,">Description:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.Description">
        
        <label class="form-label mt-1" for="name,">bed:</label>
        <input class="form-control mb-2" type="number" asp-for="@Model.bed">


        <label class="form-label mt-1" for="name,">bath:</label>
        <input class="form-control mb-2" type="number" asp-for="@Model.bath">


        <label class="form-label mt-1" for="name,">photo Name:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.photo">

        <button asp-page-handler="submit" class="btn btn-success mt-2">Add</button>
        <button asp-page-handler="cancel" class="btn btn-outline-secondary mt-2">Cancel</button>
    </form>

</div>

Hotel/Pages/AddServes.cshtml
@page
@model Hotel.Pages.AddServesModel
@{
    ViewData["Title"] = "Add Serves";
}

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-success" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<br />
<br />
<br />
<br />
<br />

<div class="text-left">
    <br />
    <h1 class="text-lg-center fs-5">Add Serves</h1>
    <form method="post">
        <label class="form-label " for="ID">Serves Name:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.ServesName">\

        <label class="form-label mt-1" for="name,">Description:</label>
        <input class="form-control mb-2" type="text" asp-for="@Model.Description">

        <label class="form-label mt-1" for="name,">Price:</label>
        <input class="form-control mb-2" type="number" asp-for="@Model.Price">


        <label class="form-label mt-1" for="name,">icon:</label>
        <input class="form-control mb-2" type="number" asp-for="@Model.icon">


        

        <button asp-page-handler="submit" class="btn btn-success mt-2">Add</button>
        <button asp-page-handler="cancel" class="btn btn-outline-secondary mt-2">Cancel</button>
    </form>

</div>

Hotel/Pages/ReservationHistory.cshtml
@page
@model Hotel.Pages.ReservationHistoryModel
@{
    ViewData["Title"] = "Reservation History";
}
<br />
<br />
<br />
<br />
<div class="text-center">
    <h1 class="display-4">Welcome, @User.Identity.Name!</h1>
    <p class="text-lg-start fs-3">Total Reservation: @Model.Table.Rows.Count</p>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">ReservationID</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">CheckInDate</th>
                <th scope="col">CheckOutDate</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < @Model.Table.Rows.Count; i++)
            {
                <tr>

                    <th scope="row">@(i + 1)</th>
                    <td>@Model.Table.Rows[i][0]</td>
                    <td>@Model.Table.Rows[i][1]</td>
                    <td>@Model.Table.Rows[i][3]</td>
                    <td>@Model.Table.Rows[i][4]</td>
                    @* @for (int j = 0; j < Model.Table.Columns.Count; j++)
                    {
                        <td>@Model.Table.Rows[i][j]</td>
                    } *@
                </tr>
            }
        </tbody>
    </table>

</div>

Hotel/Pages/Userpage.cshtml
@page
@model Hotel.Pages.UserpageModel
@{
    ViewData["Title"] = "User page";
}
@* <br />
<br />
<br />
<br />
<br />
<br />
<div class="text-center">
    <h1 class="mb-2">Welcome, @Model.Username!</h1>
    <div>
        <button class="btn btn-primary" onclick="location.href='UpdateUserData'">Update Data</button>
        <button class="btn btn-info" onclick="location.href='ReservationHistory'">View Reservation History</button>
    </div>
</div> *@

<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-success" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login and Sign Up</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>


        .locontainer {
            max-width: 400px;
            margin-top: 50px;
        }
    </style>
</head>
<body>

    <div class="locontainer">
        <form method="post">
            <hr>
            <h1 class="mb-2">Welcome, @Model.Username1!</h1>
            <hr>
            <button asp-page-handler="submit" class="btn btn-success mt-2">Update Data</button>
            <button asp-page-handler="submit1" class="btn btn-success mt-2">View Reservation History</button>
            <button asp-page-handler="submit2" class="btn btn-success mt-2" >Give US Your FeedBack</button>
            <button asp-page-handler="submit3" class="btn btn-success mt-2" >Make Reservation</button>
            <hr>
        </form>
        @* <hr>
        <h1 class="mb-2">Welcome, @Model.Username!</h1>
        <button asp-page-handler="submit" class="btn btn-success mt-2">Update Data</button>
        <button asp-page-handler="submit1" class="btn btn-success mt-2">View Reservation History</button>
        <hr> *@
        
    </div>

</body>
</html>

Hotel/Pages/loginHE.cshtml
@page
@model Hotel.Pages.loginHEModel
@{
    ViewData["Title"] = "Login";
}
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-success" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login and Sign Up</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<style>


    .locontainer {
        max-width: 400px;
        margin-top: 50px;
    }
</style>
<div class="locontainer">
    @if (!string.IsNullOrEmpty(Model.UserError))
    {
        <div class="alert alert-danger" role="alert">
            @Model.UserError
        </div>
    }
    <!-- Login Form -->
    <hr>
    <form id="loginForm" method="post">
        <h2 class="text-center mb-4">Login Employee</h2>
        <label class="form-label mt-1" for="Usrename">Login As:</label>
        <select asp-for="@Model.Select" class="form-select text-black bg-transparent" id="RoomN" aria-label="Login As">
            <option class="text-black" selected disabled>Select your Choice</option>
            <option class="text-black" value="Admin">Admin</option>
            <option class="text-black" value="Manager">Manager</option>
            <option class="text-black" value="Staff">Staff</option>

            
        </select>
        <div class="form-group">
            <label class="form-label mt-1" for="Usrename">Username:</label>
            <input class="form-control mb-2" type="text" asp-for="@Model.Username">
            <span asp-validation-for="@Model.Username" class="text-danger"></span>

        </div>
        <div class="form-group">
            <label class="form-label mt-1" for="password,">password:</label>
            <input class="form-control mb-2" type="password" asp-for="@Model.Password">
            <span asp-validation-for="@Model.Password" class="text-danger"></span>

        </div>
        <button asp-page-handler="submit" class="btn btn-success mt-2">Login</button>

    </form>
    <hr />
    @* <form id="loginForm">
    <h2 class="text-center mb-4">Login</h2>
    <div class="form-group">
    <label for="loginEmail">Email address</label>
    <input type="email" class="form-control" id="loginEmail" placeholder="Enter email" required>
    </div>
    <div class="form-group">
    <label for="loginPassword">Password</label>
    <input type="password" class="form-control" id="loginPassword" placeholder="Password" required>
    </div>
    <button type="submit" class="btn btn-success btn-block" href="Index">Login</button>
    </form> *@
    

</div>